;--------------------------------------------------------------------------------
;				DOS INCLUDES
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; Designed for:		WolfRAM
; developed by:		Subhajit Sahu
;
; For more details go through the README file
;********************************************************************************






INCLUDE		dos_vals.inc
INCLUDE		dos_macr.inc



