;--------------------------------------------------------------------------------
;				MEMORY CONTROL
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; Designed for:		WolfRAM
; developed by:		Subhajit Sahu
;
; For more details go through the README file
;********************************************************************************





INCLUDE		mem_vals.inc
INCLUDE		mem_data.inc
INCLUDE		mem_macr.inc

