;--------------------------------------------------------------------------------
;			EMS USAGE DETAILS
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************
;
;
;
;
;
; PAGE 00
; 	XMS use page.
;
; PAGE 01
;	Rough EMS page1
;
; PAGE 02
;	Rough EMS page2
;
; PAGE 03
;	Rough EMS page3
;
; PAGE 04
;	Rough EMS page4
;
; PAGE 05
;	016 Palettes storage[12K]		256x3
;	016 Mouse IMGs[16.25K]			32x32
;	001 PC Speaker Sound[0.5K]		512x1
;	256 File Handles[4K]			16x256
;	**Voice Tables----031 General PICs[31K]			32x32
;
; PAGE 06
;	Font page 1.
;
; PAGE 07
;	Font page 2.
;
; PAGE 08
;	SoundBlaster Audio page 1
;
; PAGE 09
;	SoundBlaster Audio page 2
;
; PAGE 10
;	004 General Audios			4x16K
;
; PAGE 11
;	064 General PICs			64x1K
;
; PAGE 12
;	Video Page1
;
; PAGE 13
;	Video Page2
;
; PAGE 14
;	Video Page3
;
; PAGE 15
;	Video Page4
;
; PAGE 16 onwards
;	Useable as per choice page
;
;
;
;
;
