;--------------------------------------------------------------------------------
;               FUNCTION AVAILABLE FILE
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
;
; Version: first
; by WolfRAM
;********************************************************************************
;
;
;
;::::::::::::::::::::::::::::::::
; MAIN functions
;::::::::::::::::::::::::::::::::
; HZDstart ()
; HZDstop ()
; HZDlastError% ()
;
;
;
;
;::::::::::::::::::::::::::::::::
; MEMORY MACHINE functions
;::::::::::::::::::::::::::::::::
;HZDgetMemory& (BYVAL typ%, BYVAL Segm%, BYVAL Offs&)
;HZDcopyMemory (BYVAL srctype%, BYVAL srcSeg%, BYVAL srcOff&, BYVAL desttype%, BYVAL destSeg%, BYVAL destOff&, BYVAL bytes&)
;HZDcopyString (BYVAL srctype%, BYVAL srcSeg%, BYVAL srcOff&, BYVAL desttype%, BYVAL destSeg%, BYVAL destOff&)
;HZDgetString$ (BYVAL srctype%, BYVAL srcSeg%, BYVAL srcOff&)
;HZDputString (BYVAL x%, BYVAL y%, BYVAL z%, BYVAL destype%, BYVAL desSeg%, BYVAL desOff&)
;
