;--------------------------------------------------------------------------------
;			MOUSE IMG DETAILS
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************
;
;
;
;
;
; 00	WORD	HotSpotX
; 02	WORD	HotSpotY
; 04	BYTE	32x32 Image
;
; HotSpot details size	-	0004 bytes
; Image Size		-	1024 bytes
; Total Size		-	1028 bytes
;
; Total number of Mouse IMGs present	-	16
; Total space required			-	16640 bytes
; 						[16.25K]
; EMS page used	-	4
; EMS offset	-	12288
;			[3000h]
;
;
;
;
;


