;--------------------------------------------------------------------------------
;			SPECIAL FILE TYPES
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


datatypegraphicspage			equ	0
datatypegetput				equ	1
datatypepcspeaker				equ	0
datatypekeycontrols				equ	0