;--------------------------------------------------------------------------------
;			EMS PAGE USE DETAILS
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


xmsuseOFF		equ	0
roughOFF			equ	0
findfileOFF		equ	0
paletteuseOFF		equ	0
mouseimgOFF		equ	3000h
pcspeakerOFF		equ	7000h
filehandlesOFF		equ	7200h
soundtablesOFF		equ	8200h
font1OFF			equ	0
font2OFF			equ	0
sound1OFF		equ	0
sound2OFF		equ	0
generalsoundsOFF		equ	0
generalpicsOFF		equ	0
video1OFF		equ	0
video2OFF		equ	0
video3OFF		equ	0
video4OFF		equ	0






