;--------------------------------------------------------------------------------
;		KEYBOARD RELATED CONSTANTS
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************




KeyBuuSize		equ	128			;Buffer Size
KeyBuuFirst		equ	0			;Buffer Start(0)
KeyBuuLast		equ	128			;Buffer End(Start+Size)
