;--------------------------------------------------------------------------------
;			LIBRARY READ AND SAVE FILE OFFSETS FILE
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


oldpaletteADRS		equ	0
defpaletteADRS		equ	0
