;--------------------------------------------------------------------------------
;			LIBRARY READ FILE OFFSETS FILE
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


libreadnum			equ	255
defpaletteADRS			equ	0
screenshotdataADRS		equ	0
screenshotdataSIZE			equ	0
screenshotxresOFF			equ	0
screenshotyresOFF			equ	0
screenshotheaderSIZE		equ	0
screenshotfilesizeOFF		equ	0
keydefcontrolsADRS			equ	0
keydefcontrolsSIZE			equ	12*8
