;--------------------------------------------------------------------------------
;			USEFUL CONSTANTS
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************



;*****Constants*****


;parameters
param1		equ	[bp+6]
param2		equ	[bp+8]
param3		equ	[bp+10]
param4		equ	[bp+12]
param5		equ	[bp+14]
param6		equ	[bp+16]
param7		equ	[bp+18]
param8		equ	[bp+20]
param9		equ	[bp+22]
param10		equ	[bp+24]
param11		equ	[bp+26]
param12		equ	[bp+28]


;stacks
stack0		equ	[bp]
stack1		equ	[bp+01]
stack2		equ	[bp+02]
stack3		equ	[bp+03]
stack4		equ	[bp+04]
stack5		equ	[bp+05]
stack6		equ	[bp+06]
stack7		equ	[bp+07]
stack8		equ	[bp+08]
stack9		equ	[bp+09]
stack10		equ	[bp+10]
stack11		equ	[bp+11]
stack12		equ	[bp+12]
stack13		equ	[bp+13]
stack14		equ	[bp+14]
stack15		equ	[bp+15]
stack16		equ	[bp+16]
stack17		equ	[bp+17]
stack18		equ	[bp+18]
stack19		equ	[bp+19]
stack20		equ	[bp+20]
stack21		equ	[bp+21]
stack22		equ	[bp+22]
stack23		equ	[bp+23]
stack24		equ	[bp+24]
stack25		equ	[bp+25]
stack26		equ	[bp+26]
stack27		equ	[bp+27]
stack28		equ	[bp+28]
stack29		equ	[bp+29]
stack30		equ	[bp+30]
stack31		equ	[bp+31]
stack32		equ	[bp+32]
stack33		equ	[bp+33]
stack34		equ	[bp+34]
stack35		equ	[bp+35]
stack36		equ	[bp+36]
stack37		equ	[bp+37]
stack38		equ	[bp+38]
stack39		equ	[bp+39]
