;--------------------------------------------------------------------------------
;			ERROR LIST
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************



;*****Error numbers*****
errnoems				equ	1
errnoxms				equ	2
errlowems				equ	3
errlowxms				equ	4
errwrongpalettelocation		equ	5
errfilenotopen			equ	6
erropenfile			equ	7
errfilenumused			equ	8
errclosefile			equ	9
errnofreefile			equ	10
errseekfile			equ	11
errreadfile			equ	12
errwritefile			equ	13
errfilenumnotused			equ	14
errdeletefile			equ	15
errcreatefile			equ	16
errnotspfile			equ	17
errdatapacknotavailable		equ	18
errstringtoolarge			equ	19
errimproperrefreshrate		equ	20
errgetputdata			equ	21
errnotgraphicspage			equ	22
errfilenotused			equ	23
errdatatypewrong			equ	24
errfindfile			equ	25



