;--------------------------------------------------------------------------------
;			USEFUL INCLUDER FILE
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


INCLUDE	Datatype.inc
INCLUDE	Libread.inc
INCLUDE	Libsave.inc
INCLUDE	Macros.inc
INCLUDE Pushes.inc
INCLUDE Consts.inc
INCLUDE Errors.inc
INCLUDE	Emsuse.inc