;--------------------------------------------------------------------------------
;			LIBRARY SAVE FILE OFFSETS FILE
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; by WolfRAM
;********************************************************************************


libsavenum		equ	254
oldpaletteADRS		equ	0
