;--------------------------------------------------------------------------------
;				ERROR VALUES
;--------------------------------------------------------------------------------
; Part of HAZARD Library
; (a game/software programming library for QuickBasic 4.5 or similar)
; 
; Version: first
; Designed for:		WolfRAM
; developed by:		Subhajit Sahu
;
; For more details go through the README file
;********************************************************************************






;======================DOS Extented Error Getting======================
_dos_get_extended_error_information				equ	59h
;======================DOS Extented Error Getting======================




;======================Error Categories======================
_error_dos							equ	00h
_error_ems							equ	10h
_error_xms							equ	11h
;======================Error Categories======================
